/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/BYXTHaNtY2S
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import Link from "next/link"


export function About() {
  return (
    <main className="flex flex-col items-center justify-center w-full min-h-screen bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-gray-100 px-4 md:px-6 lg:px-8 py-12 md:py-16 lg:py-20">
      <div className="container max-w-6xl">
        <section className="flex flex-col md:flex-row items-center justify-between gap-8 mb-12 md:mb-16 lg:mb-20">
          <div className="flex flex-col items-center md:items-start text-center md:text-left">
            <h1 className="text-4xl md:text-5xl font-bold mb-2">Arminder Chahal</h1>
            <h2 className="text-2xl md:text-3xl font-medium mb-4 text-gray-600 dark:text-gray-400">Data Analyst</h2>
            <p className="max-w-md text-gray-700 dark:text-gray-300">
              Detail-oriented Data Analyst with a robust background in Java development and data-driven
              decision making. Proficient in Python, SQL, and advanced analytics, adept at transforming
              complex datasets into actionable insights. Committed to enhancing data accuracy and utility to
              drive business solutions.
            </p>
          </div>
          <img
            src="../public/profile.jpg"
            alt="Arminder Kaur"
            className="rounded-full w-32 h-32 md:w-40 md:h-40"
            style={{
              aspectRatio: "200/200",
              objectFit: "cover",
            }}
            width="200"
            height="200"
           
          />
        </section>
        <section className="mb-12 md:mb-16 lg:mb-20">
          <h2 className="text-3xl font-bold mb-6">Projects</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            <Card>
              <CardHeader>
                <CardTitle>Covid Outcome Prediction</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-gray-700 dark:text-gray-300 mb-4">
                  Predicted the outcome of COVID cases using Keras, sklearn, and matplotlib to analyze and clean Ontario
                  COVID dataset. Explored different architectures of DNNs and RNNs to predict the outcome of each case.
                </p>
                <div className="flex gap-2">
                  <Link href="#" className="text-blue-500 hover:text-blue-600 dark:text-blue-400 dark:hover:text-blue-500">
                    GitHub
                  </Link>
                  <Link href="#" className="text-blue-500 hover:text-blue-600 dark:text-blue-400 dark:hover:text-blue-500">
                    Live Demo
                  </Link>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Fake News Detection</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-gray-700 dark:text-gray-300 mb-4">
                  Used fake news detection dataset to train data model to predict whether a news article is real or fake.
                </p>
                <div className="flex gap-2">
                  <Link href="#" className="text-blue-500 hover:text-blue-600 dark:text-blue-400 dark:hover:text-blue-500">
                    GitHub
                  </Link>
                  <Link href="#" className="text-blue-500 hover:text-blue-600 dark:text-blue-400 dark:hover:text-blue-500">
                    Live Demo
                  </Link>
                </div>
              </CardContent>
            </Card>
          </div>
        </section>
        <section className="mb-12 md:mb-16 lg:mb-20">
          <h2 className="text-3xl font-bold mb-6">Skills</h2>
          <ul className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
            <li className="bg-gray-200 dark:bg-gray-800 rounded-md px-4 py-2 text-gray-700 dark:text-gray-300">
              Data Mining
            </li>
            <li className="bg-gray-200 dark:bg-gray-800 rounded-md px-4 py-2 text-gray-700 dark:text-gray-300">
              Business Intelligence
            </li>
            <li className="bg-gray-200 dark:bg-gray-800 rounded-md px-4 py-2 text-gray-700 dark:text-gray-300">
              Data Management
            </li>
            <li className="bg-gray-200 dark:bg-gray-800 rounded-md px-4 py-2 text-gray-700 dark:text-gray-300">
              Data Visualization
            </li>
            <li className="bg-gray-200 dark:bg-gray-800 rounded-md px-4 py-2 text-gray-700 dark:text-gray-300">
              Data Cleaning
            </li>
            <li className="bg-gray-200 dark:bg-gray-800 rounded-md px-4 py-2 text-gray-700 dark:text-gray-300">
              Python Programming
            </li>
            <li className="bg-gray-200 dark:bg-gray-800 rounded-md px-4 py-2 text-gray-700 dark:text-gray-300">
              Statistical Analysis
            </li>
            <li className="bg-gray-200 dark:bg-gray-800 rounded-md px-4 py-2 text-gray-700 dark:text-gray-300">
              Predictive Analytics
            </li>
            <li className="bg-gray-200 dark:bg-gray-800 rounded-md px-4 py-2 text-gray-700 dark:text-gray-300">
              Quantitative Analysis
            </li>
            <li className="bg-gray-200 dark:bg-gray-800 rounded-md px-4 py-2 text-gray-700 dark:text-gray-300">
              Problem Solving
            </li>
            <li className="bg-gray-200 dark:bg-gray-800 rounded-md px-4 py-2 text-gray-700 dark:text-gray-300">
              Team Collaboration
            </li>
          </ul>
        </section>
        <section className="mb-12 md:mb-16 lg:mb-20">
          <h2 className="text-3xl font-bold mb-6">Contact</h2>
          <div className="flex flex-col sm:flex-row items-center justify-between gap-6">
            <div className="flex flex-col items-center sm:items-start gap-2">
              <Link href="https://www.linkedin.com/in/arminder-chahal" className="flex items-center gap-2 text-blue-500 hover:text-blue-600 dark:text-blue-400 dark:hover:text-blue-500">
                <LinkedinIcon className="w-6 h-6" />
                LinkedIn
              </Link>
              <Link href="mailto:arudhatt@gmail.com" className="flex items-center gap-2 text-blue-500 hover:text-blue-600 dark:text-blue-400 dark:hover:text-blue-500">
                <MailIcon className="w-6 h-6" />
                arudhatt@gmail.com
              </Link>
            </div>
            <div className="flex flex-col items-center sm:items-start gap-2">
              {/* <Link href="#" className="flex items-center gap-2 text-blue-500 hover:text-blue-600 dark:text-blue-400 dark:hover:text-blue-500">
                <TwitterIcon className="w-6 h-6" />
                @johndoe
              </Link> */}
              <Link href="#" className="flex items-center gap-2 text-blue-500 hover:text-blue-600 dark:text-blue-400 dark:hover:text-blue-500">
                <GithubIcon className="w-6 h-6" />
                Arminder Chahal
              </Link>
            </div>
          </div>
        </section>
      </div>
    </main>
  )
}

function GithubIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function LinkedinIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function MailIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function TwitterIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}
